package:
  name: autosleap       # Replace with your package name
  version: "1.0.0"      # Replace with your version

source:
  path: .               # Use the local directory; replace with a URL or tarball if distributing remotely

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed"  # Install using pip without a setup.py
  entry_points:
    - myscript = mypackage.module:main_function  # Command-line script entry point

requirements:
  build:
    - python
    - pip                # Required for pip installation
  run:
    - python
    - numpy
    - pandas
    - pillow
    - ffmpeg

about:
  home: https://github.com/mxwllmadden/SLEAP-Autoanalysis  # Replace with your package homepage
  license: GPL                                  # Replace with your license
  summary: "A brief description of your package"

extra:
  recipe-maintainers:
    - your-github-username
