{% set name = "autosleap" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autosleap-{{ version }}.tar.gz
  sha256: 67004cbd8b0dea4ff317a2546c77781fc97bc0d22f34e0d402ba56d360af9b6d
  include:
    - assets/*

build:
  entry_points:
    - autosleap = autosleap.cli_parser:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.10
    - numpy
    - py-opencv
    - pillow
    - matplotlib-base
    - ffmpeg

test:
  imports:
    - autosleap
  commands:
    - pip check
    - autosleap --help
    - python -c "import cv2; print(cv2.__version__)"
  requires:
    - pip
    - numpy
    - py-opencv
    - pillow
    - matplotlib-base

about:
  summary: Python package to automate some aspects of SLEAP analysis.
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxwllmadden
  channel_targets:
    - conda-forge