{% set name = "autosleap" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autosleap-{{ version }}.tar.gz
  sha256: b77b65a6651cf5d6c9660848663a8a0181807e839dee491633699634fabd237a
  include:
    - assets/*

build:
  entry_points:
    - autosleap = autosleap.cli_parser:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.10
    - numpy
    - pillow
    - matplotlib-base
    - ffmpeg
    - ffmpeg-python
    - h5py

test:
  imports:
    - autosleap
  commands:
    - pip check
    - autosleap --help
  requires:
    - pip
    - numpy
    - pillow
    - matplotlib-base

about:
  summary: Python package to automate some aspects of SLEAP analysis.
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxwllmadden
  channel_targets:
    - conda-forge